from enum import Enum


class Status(Enum):
    CREATED_START = 100
    CREATED_MID = 200
    AWAITING_USER_RESPONSE = 300
    PROCESSING_USER_RESPONSE = 400
    TERMINATED_COMPLETE = 500
    TERMINATED_ERROR = 600
    TERMINATED_EXCEPTION = 700
    TERMINATED_TIMEOUT = 800
    NO_RESPONSE_REQUIRED = 900
