# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=-1)),
                ('plugin_id', models.IntegerField(default=-1)),
                ('enrollment_id', models.IntegerField(default=-1)),
                ('enrollment_name', models.CharField(max_length=25)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=-1)),
                ('plugin_id', models.IntegerField(default=-1)),
                ('token', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
